"""
Django settings for deploycenter project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import tomllib
from socket import gethostbyname, gethostname

from django.utils.translation import gettext_lazy as _

import dj_database_url
import sentry_sdk
from configurations import Configuration, values
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.dramatiq import DramatiqIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_release():
    """
    Get the current release of the application
    """
    try:
        with open(os.path.join(BASE_DIR, "pyproject.toml"), "rb") as f:
            pyproject_data = tomllib.load(f)
        return pyproject_data["project"]["version"]
    except (FileNotFoundError, KeyError):
        return "NA"  # Default: not available


class Base(Configuration):
    """
    This is the base configuration every configuration (aka environment) should inherit from. It
    is recommended to configure third-party applications by creating a configuration mixins in
    ./configurations and compose the Base configuration with those mixins.

    It depends on an environment variable that SHOULD be defined:

    * DJANGO_SECRET_KEY

    You may also want to override default configuration by setting the following environment
    variables:

    * SENTRY_DSN
    * DB_NAME
    * DB_HOST
    * DB_PASSWORD
    * DB_USER

    Every variable read here is documented in docs/env.md: keep it in sync.
    """

    DEBUG = False
    USE_SWAGGER = False

    API_VERSION = "v1.0"

    # Admin URL configuration
    ADMIN_URL = values.Value("admin")

    # Security
    ALLOWED_HOSTS = values.ListValue([])
    SECRET_KEY = values.Value(None)
    SERVER_TO_SERVER_API_TOKENS = values.ListValue([])

    # Application definition
    ROOT_URLCONF = "deploycenter.urls"
    WSGI_APPLICATION = "deploycenter.wsgi.application"

    # Database
    DATABASES = {
        "default": dj_database_url.config()
        if os.environ.get("DATABASE_URL")
        else {
            "ENGINE": values.Value(
                "django.db.backends.postgresql_psycopg2",
                environ_name="DB_ENGINE",
                environ_prefix=None,
            ),
            "NAME": values.Value(
                "deploycenter", environ_name="DB_NAME", environ_prefix=None
            ),
            "USER": values.Value("dbuser", environ_name="DB_USER", environ_prefix=None),
            "PASSWORD": values.Value(
                "dbpass", environ_name="DB_PASSWORD", environ_prefix=None
            ),
            "HOST": values.Value(
                "localhost", environ_name="DB_HOST", environ_prefix=None
            ),
            "PORT": values.Value(5432, environ_name="DB_PORT", environ_prefix=None),
        }
    }
    DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

    DATA_DIR = values.Value(
        "/data", environ_name="DJANGO_DATA_DIR", environ_prefix=None
    )

    # Static files (CSS, JavaScript, Images)
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(DATA_DIR, "static")
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(DATA_DIR, "media")

    SITE_ID = 1

    # No model has a file field and no object storage is configured: the
    # default storage is the filesystem, only the static files backend can be
    # changed (see docs/env.md).
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": values.Value(
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
                environ_name="STORAGES_STATICFILES_BACKEND",
                environ_prefix=None,
            ),
        },
    }

    # Internationalization
    # https://docs.djangoproject.com/en/3.1/topics/i18n/

    # Languages
    LANGUAGE_CODE = values.Value("fr-fr")
    LANGUAGE_COOKIE_NAME = (
        "deploycenter_language"  # cookie & language is set from frontend
    )

    # Careful! Languages should be ordered by priority, as this tuple is used to get
    # fallback/default languages throughout the app.
    LANGUAGES = values.SingleNestedTupleValue((("fr-fr", _("French")),))

    LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

    TIME_ZONE = "UTC"
    USE_I18N = True
    USE_TZ = True

    # # Templates
    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [os.path.join(BASE_DIR, "templates")],
            "OPTIONS": {
                "context_processors": [
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "django.template.context_processors.csrf",
                    "django.template.context_processors.debug",
                    "django.template.context_processors.i18n",
                    "django.template.context_processors.media",
                    "django.template.context_processors.request",
                    "django.template.context_processors.tz",
                ],
                "loaders": [
                    "django.template.loaders.filesystem.Loader",
                    "django.template.loaders.app_directories.Loader",
                ],
            },
        },
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.locale.LocaleMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        # After AuthenticationMiddleware: it logs sessions out (see
        # OIDC_REQUIRE_MFA) and needs the session and user on the request.
        "core.authentication.middleware.RequireMFAMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
    ]

    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
        "core.authentication.backends.OIDCAuthenticationBackend",
    ]

    # Django applications from the highest priority to the lowest
    INSTALLED_APPS = [
        "core",
        "drf_spectacular",
        # Third party apps
        "corsheaders",
        "django_dramatiq",
        "dramatiq_crontab",
        "django_filters",
        "rest_framework",
        # Django
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.postgres",
        "django.contrib.sessions",
        "django.contrib.sites",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        # OIDC third party
        "mozilla_django_oidc",
    ]

    SPECTACULAR_SETTINGS = {
        "TITLE": "Deploy Center API",
        "DESCRIPTION": "This is the Deploy Center API schema.",
        "VERSION": "1.0.0",
        "SERVE_INCLUDE_SCHEMA": False,
        "ENABLE_DJANGO_DEPLOY_CHECK": values.BooleanValue(
            default=False,
            environ_name="SPECTACULAR_SETTINGS_ENABLE_DJANGO_DEPLOY_CHECK",
            environ_prefix=None,
        ),
        "COMPONENT_SPLIT_REQUEST": True,
        # OTHER SETTINGS
        "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
        "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
        "REDOC_DIST": "SIDECAR",
    }

    # Cache
    CACHES = {
        "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    }

    REST_FRAMEWORK = {
        # The UI authenticates with its session cookie, partners with the API
        # keys their viewsets declare. No OIDC bearer class, see
        # docs/authentication.md.
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "core.authentication.SessionAuthentication",
        ),
        "DEFAULT_PARSER_CLASSES": [
            "rest_framework.parsers.JSONParser",
        ],
        "EXCEPTION_HANDLER": "core.api.exception_handler",
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": 20,
        "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_THROTTLE_RATES": {
            "user_list_sustained": values.Value(
                default="180/hour",
                environ_name="API_USERS_LIST_THROTTLE_RATE_SUSTAINED",
                environ_prefix=None,
            ),
            "user_list_burst": values.Value(
                default="30/minute",
                environ_name="API_USERS_LIST_THROTTLE_RATE_BURST",
                environ_prefix=None,
            ),
        },
    }

    AUTH_USER_MODEL = "core.User"

    # CORS
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = values.BooleanValue(False)
    CORS_ALLOWED_ORIGINS = values.ListValue([])
    CORS_ALLOWED_ORIGIN_REGEXES = values.ListValue([])

    # Sentry
    SENTRY_DSN = values.Value(None, environ_name="SENTRY_DSN", environ_prefix=None)

    # ProConnect "api-partenaires": push of authorized email domains to OIDC
    # providers (``attached_email_domains`` on their side).
    # The secret is global to all /api/oidc_providers/* routes (not per-provider);
    # per-provider access is enforced by the api-partenaires allowlist on their side.
    PROCONNECT_API_PARTENAIRES_URL = values.Value(
        None,
        environ_name="PROCONNECT_API_PARTENAIRES_URL",
        environ_prefix=None,
    )
    PROCONNECT_API_PARTENAIRES_SECRET = values.Value(
        None,
        environ_name="PROCONNECT_API_PARTENAIRES_SECRET",
        environ_prefix=None,
    )
    # Optional SOCKS5 proxy for api-partenaires calls (to egress from a fixed IP),
    # e.g. "socks5://user:pass@proxy-host:1080". Empty = direct connection.
    PROCONNECT_API_PARTENAIRES_PROXY_URL = values.Value(
        None,
        environ_name="PROCONNECT_API_PARTENAIRES_PROXY_URL",
        environ_prefix=None,
    )
    # API key gating the allowlist route
    # (GET /api/v1.0/proconnect/oidc_providers.yaml), sent as
    # "Authorization: Bearer <key>". Empty = the route is closed to everyone.
    PROCONNECT_ALLOWLIST_VIEW_API_KEY = values.Value(
        None,
        environ_name="PROCONNECT_ALLOWLIST_VIEW_API_KEY",
        environ_prefix=None,
    )
    # Webhooks fired when an operator requests a new ProConnect domain (into the
    # "requested" bucket). Same config format as service webhooks; provided as a
    # JSON list in the env var. There is no natural per-org/per-service DB home for
    # this notification, so it is configured statically here.
    PROCONNECT_REQUESTED_DOMAIN_WEBHOOKS = values.Value(
        [],
        environ_name="PROCONNECT_REQUESTED_DOMAIN_WEBHOOKS",
        environ_prefix=None,
    )
    # Deployed ProConnect allowlist (per-idp allowed_attached_email_domains), fetched
    # from the api-partenaires repo by `proconnect_fetch_prevalidated` and cached, so
    # the UI can show which of an org's domains are already pre-validated (routable) vs
    # pending the allowlist deploy.
    PROCONNECT_DOMAIN_ALLOWLIST_URL = values.Value(
        "https://raw.githubusercontent.com/proconnect-gouv/api-partenaires/"
        "refs/heads/main/config/anct/oidc_providers.production.yaml",
        environ_name="PROCONNECT_DOMAIN_ALLOWLIST_URL",
        environ_prefix=None,
    )
    PROCONNECT_DOMAIN_ALLOWLIST_CACHE_TTL = values.IntegerValue(
        4 * 3600,  # 4 hours
        environ_name="PROCONNECT_DOMAIN_ALLOWLIST_CACHE_TTL",
        environ_prefix=None,
    )

    # Posthog
    POSTHOG_KEY = values.Value(None, environ_name="POSTHOG_KEY", environ_prefix=None)
    POSTHOG_HOST = values.Value(
        "https://eu.i.posthog.com", environ_name="POSTHOG_HOST", environ_prefix=None
    )
    POSTHOG_SURVEY_ID = values.Value(
        None, environ_name="POSTHOG_SURVEY_ID", environ_prefix=None
    )

    # Background tasks (Dramatiq), see docs/deployment.md "Background tasks".
    # Every task is periodic and dispatched by the scheduler that runs inside
    # the worker (worker.py). The broker keyspace is namespaced ("dramatiq:*"),
    # so it can share the Redis of the cache, but a queue is not a cache:
    # whatever instance it points at must be Redis 7+ and run with
    # "maxmemory-policy noeviction" and AOF persistence, or enqueued tasks can
    # be silently lost.
    TASK_BROKER_URL = values.Value(
        "redis://redis:6379", environ_name="TASK_BROKER_URL", environ_prefix=None
    )
    TASK_BROKER_NAMESPACE = values.Value(
        "dramatiq", environ_name="TASK_BROKER_NAMESPACE", environ_prefix=None
    )
    TASK_BROKER_CLASS = "dramatiq_redis_streams.StreamsBroker"

    # Skip the registration of every periodic schedule. For a first deploy to a
    # PaaS, where the scheduler would otherwise fire against an unmigrated
    # database, or to run a worker that only serves hand-sent tasks.
    DISABLE_TASK_SCHEDULE = values.BooleanValue(
        default=False, environ_name="DISABLE_TASK_SCHEDULE", environ_prefix=None
    )

    # core/tasks/__init__.py imports every task module, so this one import is
    # enough for both the worker and "manage.py crontab".
    DRAMATIQ_AUTODISCOVER_MODULES = ["tasks"]

    # The two settings below are (uppercase) methods: django-configurations
    # calls them and stores the return value. Written this way so that a
    # configuration can replace one piece of the dict — Test swaps the broker
    # class and drops its options — instead of restating the whole thing.

    def task_broker_options(self):
        """Constructor arguments of the broker class."""
        return {"url": self.TASK_BROKER_URL, "namespace": self.TASK_BROKER_NAMESPACE}

    # pylint: disable=invalid-name
    def DRAMATIQ_BROKER(self):
        """Broker configuration consumed by django_dramatiq."""
        return {
            "BROKER": self.TASK_BROKER_CLASS,
            "OPTIONS": self.task_broker_options(),
            # Dramatiq runs before_* hooks in list order and after_* in
            # reverse. No Prometheus (it binds a port), no results backend
            # (nothing polls a task).
            "MIDDLEWARE": [
                "dramatiq.middleware.AgeLimit",
                "dramatiq.middleware.TimeLimit",
                "dramatiq.middleware.Callbacks",
                "dramatiq.middleware.Retries",
                # One row per task run in the admin (django_dramatiq.Task):
                # the way to check that a schedule fired and how it went.
                "django_dramatiq.middleware.AdminMiddleware",
                # Recycles connections closed by Postgres between messages;
                # without it a worker idling past CONN_MAX_AGE fails its next
                # task.
                "django_dramatiq.middleware.DbConnectionsMiddleware",
            ],
        }

    def DRAMATIQ_CRONTAB(self):
        """Scheduler configuration (dramatiq-crontab).

        The scheduler takes a Redis lock so exactly one instance is live at a
        time, however many workers run. The long blocking timeout makes every
        other worker's scheduler *wait* on that lock rather than give up, so a
        dead leader is replaced in seconds instead of leaving the schedule
        unattended until someone restarts a worker.
        """
        return {"REDIS_URL": self.TASK_BROKER_URL, "LOCK_BLOCKING_TIMEOUT": 3600}

    # pylint: enable=invalid-name

    # Session
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    SESSION_COOKIE_AGE = 60 * 60 * 12

    # OIDC - Authorization Code Flow
    OIDC_CREATE_USER = values.BooleanValue(
        default=True, environ_name="OIDC_CREATE_USER", environ_prefix=None
    )
    OIDC_RP_SIGN_ALGO = values.Value(
        "RS256", environ_name="OIDC_RP_SIGN_ALGO", environ_prefix=None
    )
    OIDC_RP_CLIENT_ID = values.Value(
        "st_deploycenter", environ_name="OIDC_RP_CLIENT_ID", environ_prefix=None
    )
    OIDC_RP_CLIENT_SECRET = values.Value(
        None,
        environ_name="OIDC_RP_CLIENT_SECRET",
        environ_prefix=None,
    )
    OIDC_OP_JWKS_ENDPOINT = values.Value(
        environ_name="OIDC_OP_JWKS_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_AUTHORIZATION_ENDPOINT = values.Value(
        environ_name="OIDC_OP_AUTHORIZATION_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_TOKEN_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_TOKEN_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_USER_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_USER_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_LOGOUT_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_LOGOUT_ENDPOINT", environ_prefix=None
    )
    OIDC_AUTH_REQUEST_EXTRA_PARAMS = values.DictValue(
        {}, environ_name="OIDC_AUTH_REQUEST_EXTRA_PARAMS", environ_prefix=None
    )
    OIDC_RP_SCOPES = values.Value(
        "openid email", environ_name="OIDC_RP_SCOPES", environ_prefix=None
    )
    # Require multi-factor authentication for every OIDC login. Off by default.
    # When on, the authorization request asks for an essential "acr" claim and
    # the value returned in the id_token is checked back, as ProConnect requires:
    # https://partenaires.proconnect.gouv.fr/docs/fournisseur-service/double_authentification
    OIDC_REQUIRE_MFA = values.BooleanValue(
        default=False, environ_name="OIDC_REQUIRE_MFA", environ_prefix=None
    )
    # ProConnect ACR values that include a second factor. eidas0-mfa and
    # eidas1-mfa are a weak second factor, eidas2 and eidas3 a strong one:
    # https://partenaires.proconnect.gouv.fr/docs/fournisseur-service/niveaux-eidas
    OIDC_MFA_ACR_VALUES = values.ListValue(
        default=["eidas0-mfa", "eidas1-mfa", "eidas2", "eidas3"],
        environ_name="OIDC_MFA_ACR_VALUES",
        environ_prefix=None,
    )
    LOGIN_REDIRECT_URL = values.Value(
        None, environ_name="LOGIN_REDIRECT_URL", environ_prefix=None
    )
    LOGIN_REDIRECT_URL_FAILURE = values.Value(
        None, environ_name="LOGIN_REDIRECT_URL_FAILURE", environ_prefix=None
    )
    LOGOUT_REDIRECT_URL = values.Value(
        None, environ_name="LOGOUT_REDIRECT_URL", environ_prefix=None
    )
    OIDC_USE_NONCE = values.BooleanValue(
        default=True, environ_name="OIDC_USE_NONCE", environ_prefix=None
    )
    OIDC_REDIRECT_REQUIRE_HTTPS = values.BooleanValue(
        default=False, environ_name="OIDC_REDIRECT_REQUIRE_HTTPS", environ_prefix=None
    )
    OIDC_REDIRECT_ALLOWED_HOSTS = values.ListValue(
        default=[], environ_name="OIDC_REDIRECT_ALLOWED_HOSTS", environ_prefix=None
    )
    OIDC_STORE_ID_TOKEN = values.BooleanValue(
        default=True, environ_name="OIDC_STORE_ID_TOKEN", environ_prefix=None
    )
    OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION = values.BooleanValue(
        default=True,
        environ_name="OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION",
        environ_prefix=None,
    )

    # WARNING: Enabling this setting allows multiple user accounts to share the same email
    # address. This may cause security issues and is not recommended for production use when
    # email is activated as fallback for identification (see previous setting).
    OIDC_ALLOW_DUPLICATE_EMAILS = values.BooleanValue(
        default=False,
        environ_name="OIDC_ALLOW_DUPLICATE_EMAILS",
        environ_prefix=None,
    )

    USER_OIDC_ESSENTIAL_CLAIMS = values.ListValue(
        default=[], environ_name="USER_OIDC_ESSENTIAL_CLAIMS", environ_prefix=None
    )
    USER_OIDC_FIELDS_TO_FULLNAME = values.ListValue(
        default=["first_name", "last_name"],
        environ_name="USER_OIDC_FIELDS_TO_FULLNAME",
        environ_prefix=None,
    )
    USER_OIDC_FIELD_TO_SHORTNAME = values.Value(
        default="first_name",
        environ_name="USER_OIDC_FIELD_TO_SHORTNAME",
        environ_prefix=None,
    )

    ALLOW_LOGOUT_GET_METHOD = values.BooleanValue(
        default=True, environ_name="ALLOW_LOGOUT_GET_METHOD", environ_prefix=None
    )

    # Logging
    # We want to make it easy to log to console but by default we log production
    # to Sentry and don't want to log to console.
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "{asctime} {name} {levelname} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
        },
        # Override root logger to send it to console
        "root": {
            "handlers": ["console"],
            "level": values.Value(
                "INFO", environ_name="LOGGING_LEVEL_LOGGERS_ROOT", environ_prefix=None
            ),
        },
        "loggers": {
            "core": {
                "handlers": ["console"],
                "level": values.Value(
                    "INFO",
                    environ_name="LOGGING_LEVEL_LOGGERS_APP",
                    environ_prefix=None,
                ),
                "propagate": False,
            },
            # The scheduler logs every job it dispatches at INFO, including
            # its own lock refresh every few seconds. The task history in the
            # admin is the record of what ran.
            "apscheduler.executors.default": {"level": "WARNING"},
        },
    }

    DATA_GOUV_API_KEY = values.Value(
        None, environ_name="DATA_GOUV_API_KEY", environ_prefix=None
    )

    METRICS_API_KEY = values.Value(
        None, environ_name="METRICS_API_KEY", environ_prefix=None
    )

    # Key gating the read-only domains export (GET /api/v1.0/domains/), used by the
    # external job generating DNS zones. Sent as "Authorization: Bearer <key>".
    # Empty = the route is closed to everyone.
    DOMAINS_API_KEY = values.Value(
        None, environ_name="DOMAINS_API_KEY", environ_prefix=None
    )

    # The nameservers a domain declared through the domains service must be
    # delegated to. The DNS check compares a domain's NS records against this list.
    DOMAINS_NAMESERVERS = values.ListValue(
        ["ns1.lst-domaines.fr", "ns2.lst-domaines.fr"],
        environ_name="DOMAINS_NAMESERVERS",
        environ_prefix=None,
    )

    # Per-query timeout of the DNS check, in seconds — the conventional resolver
    # default (dig, resolv.conf). An authoritative server that is up answers in
    # milliseconds; this budget is for the far and the lossy ones (overseas
    # départements especially), not for the healthy case.
    DOMAINS_DNS_TIMEOUT = values.FloatValue(
        5.0, environ_name="DOMAINS_DNS_TIMEOUT", environ_prefix=None
    )

    # Wall-clock cap on resolving one name, in seconds. Independent of the per-query
    # timeout on purpose: a lookup is several queries (TLD, then the authoritative
    # servers, plus any glueless NS to chase, plus retries), so tying the two
    # together makes lowering one silently starve the other.
    # Must stay below core.services.dns.BATCH_TIMEOUT, which itself has to leave the
    # request under the platform router's 30s timeout — see the budget chain there.
    DOMAINS_DNS_MAX_RESOLUTION_TIME = values.FloatValue(
        15.0, environ_name="DOMAINS_DNS_MAX_RESOLUTION_TIME", environ_prefix=None
    )

    SUITE_TERRITORIALE_BASE_URL = values.Value(
        "https://suiteterritoriale.anct.gouv.fr",
        environ_name="SUITE_TERRITORIALE_BASE_URL",
        environ_prefix=None,
    )

    API_PUBLIC_URL = values.Value(
        None, environ_name="API_PUBLIC_URL", environ_prefix=None
    )

    OPERATOR_CONTRIBUTION_POPULATION_THRESHOLD = values.IntegerValue(
        3500,
        environ_name="OPERATOR_CONTRIBUTION_POPULATION_THRESHOLD",
        environ_prefix=None,
    )
    OPERATOR_CONTRIBUTION_PER_POPULATION = values.FloatValue(
        0.01, environ_name="OPERATOR_CONTRIBUTION_PER_POPULATION", environ_prefix=None
    )
    OPERATOR_CONTRIBUTION_MAXIMUM_BASE = values.FloatValue(
        10000, environ_name="OPERATOR_CONTRIBUTION_MAXIMUM_BASE", environ_prefix=None
    )

    # pylint: disable=invalid-name
    @property
    def ENVIRONMENT(self):
        """Environment in which the application is launched."""
        return self.__class__.__name__.lower()

    # pylint: disable=invalid-name
    @property
    def RELEASE(self):
        """
        Return the release information.

        Delegate to the module function to enable easier testing.
        """
        return get_release()

    @classmethod
    def post_setup(cls):
        """Post setup configuration.
        This is the place where you can configure settings that require other
        settings to be loaded.
        """
        super().post_setup()

        # The SENTRY_DSN setting should be available to activate sentry for an environment
        if cls.SENTRY_DSN is not None:
            sentry_sdk.init(
                dsn=cls.SENTRY_DSN,
                environment=cls.__name__.lower(),
                release=get_release(),
                integrations=[DjangoIntegration(), DramatiqIntegration()],
            )
            sentry_sdk.set_tag("application", "backend")

        if (
            cls.OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION
            and cls.OIDC_ALLOW_DUPLICATE_EMAILS
        ):
            raise ValueError(
                "Both OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION and "
                "OIDC_ALLOW_DUPLICATE_EMAILS cannot be set to True simultaneously. "
            )


class Build(Base):
    """Settings used when the application is built.

    This environment should not be used to run the application. Just to build it with non-blocking
    settings.
    """

    SECRET_KEY = values.Value("DummyKey")


class Development(Base):
    """
    Development environment settings

    We set DEBUG to True and configure the server to respond from all hosts.
    """

    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8960",
        "http://localhost:8961",
        "http://localhost:8962",
        "http://localhost:3000",
    ]
    DEBUG = True

    SESSION_COOKIE_NAME = "st_deploycenter_sessionid"

    USE_SWAGGER = True
    SESSION_CACHE_ALIAS = "session"
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
        "session": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": values.Value(
                "redis://redis:6379",
                environ_name="REDIS_URL",
                environ_prefix=None,
            ),
            "TIMEOUT": values.IntegerValue(
                30,  # timeout in seconds
                environ_name="CACHES_DEFAULT_TIMEOUT",
                environ_prefix=None,
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        },
    }

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    }

    # pylint: disable=invalid-name
    def __init__(self):
        super().__init__()
        # pylint: disable=invalid-name
        self.MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]
        self.INSTALLED_APPS += ["django_extensions", "debug_toolbar"]


class DevelopmentMinimal(Development):
    """
    Development environment settings with minimal dependencies
    """

    # No Redis, so no broker to reach: the in-process stub accepts what is
    # enqueued and nothing consumes it. Nothing here enqueues anyway (the
    # schedule is off and no request path sends a task); run a task by hand
    # with "manage.py run_task", which calls it inline.
    TASK_BROKER_CLASS = "dramatiq.brokers.stub.StubBroker"
    DISABLE_TASK_SCHEDULE = True

    def task_broker_options(self):
        return {}

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
        "session": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    }


class Test(Base):
    """Test environment settings"""

    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]
    USE_SWAGGER = True

    # In-process broker: nothing is enqueued anywhere, the tests call the
    # tasks directly.
    TASK_BROKER_CLASS = "dramatiq.brokers.stub.StubBroker"

    def task_broker_options(self):
        return {}


class ContinuousIntegration(Test):
    """
    Continuous Integration environment settings

    nota bene: it should inherit from the Test environment.
    """


class Production(Base):
    """
    Production environment settings

    You must define the ALLOWED_HOSTS environment variable in Production
    configuration (and derived configurations):
    ALLOWED_HOSTS=["foo.com", "foo.fr"]
    """

    # Security
    # Add allowed host from environment variables.
    # The machine hostname is added by default,
    # it makes the application pingable by a load balancer on the same machine by example
    ALLOWED_HOSTS = [
        *values.ListValue([], environ_name="ALLOWED_HOSTS"),
        gethostbyname(gethostname()),
    ]
    CSRF_TRUSTED_ORIGINS = values.ListValue([])
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # SECURE_PROXY_SSL_HEADER allows to fix the scheme in Django's HttpRequest
    # object when your application is behind a reverse proxy.
    #
    # Keep this SECURE_PROXY_SSL_HEADER configuration only if :
    # - your Django app is behind a proxy.
    # - your proxy strips the X-Forwarded-Proto header from all incoming requests
    # - Your proxy sets the X-Forwarded-Proto header and sends it to Django
    #
    # In other cases, you should comment the following line to avoid security issues.
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = ["^__lbheartbeat__", "^__heartbeat__"]

    # Modern browsers require to have the `secure` attribute on cookies with `Samesite=none`
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # Privacy
    SECURE_REFERRER_POLICY = "same-origin"

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": values.Value(
                "redis://redis:6379",
                environ_name="REDIS_URL",
                environ_prefix=None,
            ),
            "TIMEOUT": values.IntegerValue(
                30,  # timeout in seconds
                environ_name="CACHES_DEFAULT_TIMEOUT",
                environ_prefix=None,
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        },
    }


class Feature(Production):
    """
    Feature environment settings

    nota bene: it should inherit from the Production environment.
    """


class Staging(Production):
    """
    Staging environment settings

    nota bene: it should inherit from the Production environment.
    """


class PreProduction(Production):
    """
    Pre-production environment settings

    nota bene: it should inherit from the Production environment.
    """
