# Generated by Django 5.2.6 on 2025-10-03 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorServiceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('display_priority', models.IntegerField(default=0, help_text='Priority of the operator and service for display', verbose_name='display priority')),
                ('operator', models.ForeignKey(help_text='Operator with a service configuration', on_delete=django.db.models.deletion.CASCADE, to='core.operator', verbose_name='operator')),
                ('service', models.ForeignKey(help_text='Service with a configuration', on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'operator service config',
                'verbose_name_plural': 'operator service configs',
                'db_table': 'deploycenter_operator_service_config',
                'ordering': ['operator__name', 'service__name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='operators',
            field=models.ManyToManyField(help_text='Operators with a configuration for this service', related_name='services', through='core.OperatorServiceConfig', to='core.operator', verbose_name='operators'),
        ),
        migrations.AddConstraint(
            model_name='operatorserviceconfig',
            constraint=models.UniqueConstraint(fields=('operator', 'service'), name='unique_operator_service'),
        ),
    ]
