# Generated by Django 5.2.6 on 2025-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_organization_search_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'type', 'url', 'created_at'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='code_insee',
            field=models.CharField(blank=True, help_text='INSEE administrative code', max_length=10, null=True, verbose_name='INSEE code'),
        ),
    ]
