# Generated by Django 5.2.6 on 2025-10-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_service_options_alter_organization_code_insee'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='operator',
            field=models.ForeignKey(help_text='Operator managing the organization', on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='core.operator', verbose_name='operator'),
            preserve_default=False,
        ),
    ]
