# Generated by Django 5.2.6 on 2025-10-24 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicesubscription_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('type', models.CharField(choices=[('drive_storage', 'Drive Storage')], help_text='Type of entitlement', max_length=50, verbose_name='type')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Base configuration data for metrics scraping and service operation', null=True, verbose_name='configuration')),
                ('account_type', models.CharField(blank=True, help_text='Type of account', max_length=50, null=True, verbose_name='account type')),
                ('account_id', models.CharField(blank=True, help_text='ID of the account', max_length=255, null=True, verbose_name='account ID')),
                ('service_subscription', models.ForeignKey(help_text='Service subscription this entitlement is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='core.servicesubscription', verbose_name='service subscription')),
            ],
            options={
                'verbose_name': 'entitlement',
                'verbose_name_plural': 'entitlements',
                'db_table': 'deploycenter_entitlement',
                'indexes': [models.Index(fields=['service_subscription'], name='deploycente_service_ae50ca_idx')],
                'unique_together': {('service_subscription', 'type', 'account_type', 'account_id')},
            },
        ),
    ]
