# Generated by Django 5.2.6 on 2025-11-26 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicesubscription_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('type', models.CharField(help_text='Type of entitlement', max_length=50, verbose_name='type')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Base configuration data for metrics scraping and service operation', null=True, verbose_name='configuration')),
                ('account_type', models.CharField(blank=True, default='', help_text='Type of account', max_length=50, verbose_name='account type')),
                ('account_id', models.CharField(blank=True, default='', help_text='ID of the account', max_length=255, verbose_name='account ID')),
            ],
            options={
                'verbose_name': 'entitlement',
                'verbose_name_plural': 'entitlements',
                'db_table': 'deploycenter_entitlement',
            },
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metric',
            name='account_id',
            field=models.CharField(blank=True, default='', help_text='ID of the account', max_length=255, verbose_name='account ID'),
        ),
        migrations.AddField(
            model_name='metric',
            name='account_type',
            field=models.CharField(blank=True, default='', help_text='Type of account', max_length=50, verbose_name='account type'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['account_type'], name='deploycente_account_f316bb_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['account_id'], name='deploycente_account_6ece76_idx'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account_type', 'account_id', 'key'), name='unique_metric_with_account_id'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='service_subscription',
            field=models.ForeignKey(help_text='Service subscription this entitlement is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='core.servicesubscription', verbose_name='service subscription'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['service_subscription'], name='deploycente_service_ae50ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('service_subscription', 'type', 'account_type', 'account_id')},
        ),
    ]
