# Generated by Django 5.2.6 on 2025-11-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicesubscription_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom configuration data', null=True, verbose_name='configuration'),
        ),
        migrations.AddField(
            model_name='operatorserviceconfig',
            name='externally_managed',
            field=models.BooleanField(default=False, help_text="Whether the subscriptions to this service are managed in the operator's own system", verbose_name='externally managed'),
        ),
    ]
