# Generated by Django 5.2.6 on 2025-10-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for the service', max_length=255, null=True, verbose_name='API key'),
        ),
    ]
