# Generated by Django 5.2.6 on 2025-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entitlement_alter_metric_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this subscription is currently active', verbose_name='active'),
        ),
    ]
