# Generated by Django 5.2.6 on 2025-11-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicesubscription_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicesubscription',
            unique_together={('organization', 'service', 'operator')},
        ),
    ]
