# Generated by Django 5.2.6 on 2025-11-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='account_id',
            field=models.CharField(blank=True, help_text='ID of the account', max_length=255, null=True, verbose_name='account ID'),
        ),
        migrations.AddField(
            model_name='metric',
            name='account_type',
            field=models.CharField(blank=True, help_text='Type of account', max_length=50, null=True, verbose_name='account type'),
        ),
    ]
