# Generated by Django 5.2.6 on 2025-12-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operator_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required_services',
            field=models.ManyToManyField(help_text='Services that are required for this service to be activated', related_name='required_by', to='core.service', verbose_name='required services'),
        ),
    ]
