# Generated by Django 5.2.6 on 2025-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_metric_account_id_metric_account_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('service', 'organization', 'account_type', 'account_id', 'key')},
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['account_type'], name='deploycente_account_f316bb_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['account_id'], name='deploycente_account_6ece76_idx'),
        ),
    ]
