# Generated by Django 5.2.6 on 2025-12-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_required_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='scope',
        ),
        migrations.AlterField(
            model_name='service',
            name='required_services',
            field=models.ManyToManyField(blank=True, help_text='Services that are required for this service to be activated', related_name='required_by', to='core.service', verbose_name='required services'),
        ),
    ]
