# Generated by Django 5.2.6 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_metric_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('account_id', None), ('account_type', None)), fields=('service', 'organization', 'key'), name='unique_metric_without_account'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('account_id', None)), fields=('service', 'organization', 'account_type', 'key'), name='unique_metric_with_account_type'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account_type', 'account_id', 'key'), name='unique_metric_with_account_id'),
        ),
    ]
