# Generated by Django 5.2.6 on 2025-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_metric_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_without_account',
        ),
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account_type',
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='account_id',
            field=models.CharField(default='', help_text='ID of the account', max_length=255, verbose_name='account ID'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='account_type',
            field=models.CharField(default='', help_text='Type of account', max_length=50, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='account_id',
            field=models.CharField(default='', help_text='ID of the account', max_length=255, verbose_name='account ID'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='account_type',
            field=models.CharField(default='', help_text='Type of account', max_length=50, verbose_name='account type'),
        ),
    ]
