# Generated by Django 5.2.6 on 2025-12-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_operator_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='instance_name',
            field=models.CharField(default='', help_text='Name of the instance of the service', max_length=255, verbose_name='instance name'),
        ),
    ]
