# Generated by Django 5.2.6 on 2025-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_metric_unique_metric_without_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='account_id',
            field=models.CharField(blank=True, default='', help_text='ID of the account', max_length=255, verbose_name='account ID'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='account_type',
            field=models.CharField(blank=True, default='', help_text='Type of account', max_length=50, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='account_id',
            field=models.CharField(blank=True, default='', help_text='ID of the account', max_length=255, verbose_name='account ID'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='account_type',
            field=models.CharField(blank=True, default='', help_text='Type of account', max_length=50, verbose_name='account type'),
        ),
    ]
