# Generated by Django 5.2.6 on 2026-01-08 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(help_text='Email address of the account', max_length=255, verbose_name='email')),
                ('external_id', models.CharField(blank=True, default='', help_text='External ID of the account', max_length=255, verbose_name='external ID')),
                ('type', models.CharField(blank=True, default='', help_text='Type of account', max_length=50, verbose_name='account type')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Array of role strings for this account', verbose_name='roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountServiceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Array of role strings for this account', verbose_name='roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account_id',
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='deploycente_account_f316bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='deploycente_account_6ece76_idx',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(help_text='Organization this account is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='metric',
            name='account',
            field=models.ForeignKey(default=None, help_text='Account this metric is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account', 'key'), name='unique_metric_with_account_id'),
        ),
        migrations.AddField(
            model_name='accountservicelink',
            name='account',
            field=models.ForeignKey(help_text='Account this service link is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='core.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='accountservicelink',
            name='service',
            field=models.ForeignKey(help_text='Service this account is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='core.service', verbose_name='service'),
        ),
    ]
