# Generated by Django 5.2.6 on 2026-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='instance_name',
            field=models.CharField(blank=True, help_text='Name of the instance of the service', max_length=255, null=True, verbose_name='instance name'),
        ),
    ]
