# Generated by Django 5.2.9 on 2026-01-19 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_service_instance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(blank=True, default='', help_text='Email address of the account', max_length=255, verbose_name='email')),
                ('external_id', models.CharField(blank=True, default='', help_text='External ID of the account', max_length=255, verbose_name='external ID')),
                ('type', models.CharField(blank=True, default='', help_text='Type of account', max_length=50, verbose_name='account type')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Array of role strings for this account', verbose_name='roles')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'deploycenter_account',
                'ordering': ["created_at", "organization__name", "type", "external_id"],
            },
        ),
        migrations.CreateModel(
            name='AccountServiceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Array of role strings for this account', verbose_name='roles')),
            ],
            options={
                'verbose_name': 'account service link',
                'verbose_name_plural': 'account service links',
                'db_table': 'deploycenter_account_service_link',
            },
        ),
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account_id',
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='deploycente_account_f316bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='deploycente_account_6ece76_idx',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(help_text='Organization this account is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.organization', verbose_name='organization'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='account_id',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this entitlement is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='core.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='metric',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this metric is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.account', verbose_name='account'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('service_subscription', 'type', 'account_type', 'account')},
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['account'], name='deploycente_account_6ece76_idx'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account', 'key'), name='unique_metric_with_account', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='accountservicelink',
            name='account',
            field=models.ForeignKey(help_text='Account this service link is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='core.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='accountservicelink',
            name='service',
            field=models.ForeignKey(help_text='Service this account is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='core.service', verbose_name='service'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization'], name='deploycente_organiz_4e9a32_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type'], name='deploycente_type_fd378d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='deploycente_email_416969_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['external_id'], name='deploycente_externa_b7e314_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['external_id', 'type', 'organization'], name='deploycente_externa_6ad34f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountservicelink',
            index=models.Index(fields=['account'], name='deploycente_account_bdc58e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountservicelink',
            index=models.Index(fields=['service'], name='deploycente_service_d062c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountservicelink',
            unique_together={('account', 'service')},
        ),
    ]
