# Generated by Django 5.2.6 on 2026-01-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_account_accountservicelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this metric is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.account', verbose_name='account'),
        ),
    ]
