# Generated by Django 5.2.6 on 2025-11-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_entitlement_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='api_key',
        ),
    ]
