# Generated by Django 5.2.9 on 2026-01-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_account_accountservicelink_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id', 'type', 'organization'), name='unique_account_external_id_per_org_type'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email', 'type', 'organization'), name='unique_account_email_per_org_type'),
        ),
    ]
