# Generated by Django 5.2.6 on 2026-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_metric_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account_id',
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['account'], name='deploycente_account_6ece76_idx'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account', 'key'), name='unique_metric_with_account'),
        ),
    ]
