# Generated by Django 5.2.9 on 2026-03-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_account_unique_account_external_id_per_org_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountservicelink',
            name='scope',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Scope restrictions for roles. Empty means unrestricted."
                    ' Example: {"domains": ["x.fr"]}'
                ),
                verbose_name="scope",
            ),
        ),
    ]
