# Generated by Django 5.2.6 on 2026-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_metric_unique_metric_with_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account',
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('service', 'organization', 'key'), name='unique_metric_without_account'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('service', 'organization', 'account', 'key'), name='unique_metric_with_account'),
        ),
    ]
