# Generated by Django 5.2.6 on 2026-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_metric_unique_metric_with_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_without_account',
        ),
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email address of the account', max_length=255, verbose_name='email'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account', 'key'), name='unique_metric_with_account'),
        ),
    ]
