# Generated by Django 5.2.12 on 2026-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_accountservicelink_single_role_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='siret',
            field=models.CharField(blank=True, default='', help_text='SIRET number of the operator organization', max_length=14, verbose_name='SIRET'),
        ),
    ]
