# Generated by Django 5.2.6 on 2026-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_metric_unique_metric_without_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_metric_with_account',
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('service', 'organization', 'account', 'key'), name='unique_metric_with_account', nulls_distinct=False),
        ),
    ]
