# Generated by Django 5.2.12 on 2026-03-17 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_operator_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='name_with_article',
            field=models.CharField(blank=True, default='', help_text="French name with article, e.g. 'le Nom', 'l'Opérateur'", max_length=255, verbose_name='name with article'),
        ),
        migrations.AddField(
            model_name='operator',
            name='status',
            field=models.CharField(blank=True, choices=[('intention', 'Intention'), ('partenaire', 'Partenaire'), ('partenaire_avec_services', 'Partenaire avec services')], help_text='Current status of the operator', max_length=30, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='operatorserviceconfig',
            name='config_override',
            field=models.JSONField(blank=True, default=dict, help_text="JSON overrides merged on top of the service's base config", verbose_name='configuration override'),
        ),
        migrations.CreateModel(
            name='OperatorResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(help_text='Name of the resource', max_length=255, verbose_name='name')),
                ('url', models.URLField(help_text='URL of the resource', verbose_name='URL')),
                ('type', models.CharField(choices=[('document_officiel', 'Document officiel'), ('autre', 'Autre')], default='autre', help_text='Type of the resource', max_length=100, verbose_name='type')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.operator', verbose_name='operator')),
            ],
            options={
                'verbose_name': 'operator resource',
                'verbose_name_plural': 'operator resources',
                'db_table': 'deploycenter_operator_resource',
                'ordering': ['operator', 'name'],
            },
        ),
    ]
