# Generated by Django 5.2.12 on 2026-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operator_name_with_article_operator_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatororganizationrole',
            name='operator_admins_have_admin_role',
            field=models.BooleanField(default=False, help_text='When enabled, users with an operator-level admin role are treated as service admins for this organization.', verbose_name='operator admins have admin role'),
        ),
    ]
