# Generated by Django 5.2.6 on 2026-01-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_metric_unique_metric_with_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitlement',
            name='account_id',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this entitlement is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='core.account', verbose_name='account'),
        ),
    ]
