# Generated by Django 5.2.12 on 2026-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_service_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='proconnect_domains',
            field=models.JSONField(blank=True, default=dict, help_text='ProConnect domain buckets by source', verbose_name='ProConnect domains'),
        ),
    ]
