# Generated by Django 5.2.17 on 2026-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_organization_proconnect_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subscriptions_api_key_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA-256 of the API key this service uses to manage its own subscriptions', max_length=64, null=True, unique=True, verbose_name='subscriptions API key hash'),
        ),
    ]
